### PR TITLE
Update spring rates to actual lower values

### PR DESCRIPTION
**Pull request by djhedges**
Turns out we actually have 350 & 300 lb springs. =(

350/250.0 * 55000
300/250.0 * 55000

Why was the original spring rate ratio different front to rear?

### CODE REVIEW

**Comment by macbethmotorsport** [comment]
> Why was the original spring rate ratio different front to rear?

you said 550 front and 500 rear. and the baseline spring rate shouldn't be the same front to rear anyway, so i'm a bit confused by the question.

**Comment by macbethmotorsport** [comment]
besides 350/300 is too soft. get harder springs.

**Review by macbethmotorsport — COMMENTED** [review]
cool for temporary testing, but 550/500 was already too soft.. this is now waayyyy too soft.

**Comment by djhedges** [comment]
I fully agree it's too soft but it's what we have atm.

**Pull request merged**
